# Rprompt and transient prompt features only available on nu, fish, zsh, ps, cmd

console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  white = '#F2F2F0'
  black = '#262B44'
  red = '#D4452C'
  sandstone = '#DE913E'
  green = '#49AB44'
  cobalt = '#1478DB'
  indigo = '#5A48A8'
  violet = '#7A306C'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ path .Path .Location }} '
    foreground = 'p:white'
    background = 'p:cobalt'
    type = 'path'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}'
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:sandstone{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}p:indigo{{ end }}',
      '{{ if gt .Behind 0 }}p:violet{{ end }}'
    ]

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'p:white'
    background = 'p:cobalt'
    type = 'status' 
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:sandstone'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 4000
      style = 'austin'

[secondary_prompt]
  template = '❯ '
  foreground = 'p:cobalt'
  background = 'transparent'

[transient_prompt]
  template = '<p:cobalt,transparent></><,p:cobalt> {{ .Folder }} </><p:cobalt,transparent></> '
  foreground = 'p:white'
  background = 'transparent'