# Requirements: Bash, JetBrainsMono Nerd Font

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
normal = {family = "JetBrainsMono Nerd Font", style="Regular"}
bold = {family = "JetBrainsMono Nerd Font", style="Bold"}
italic = {family = "JetBrainsMono Nerd Font", style="Italic"}
size = 10

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[terminal.shell]
program = "/bin/bash"

[window]
dimensions = {columns = 80, lines = 24}
decorations = "Full"
padding = {x=2, y=2}